spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ‘jdbc:mysql://localhost:3306/person-center?useSSL=false’
    username: root
    password: root
  session:
    timeout: 86400

