server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/personal-center?sslMode=REQUIRED&characterEncoding=UTF-8&connectionTimeZone=GMT%2B8&forceConnectionTimeZoneToSession=true
    url: jdbc:mysql://localhost:3306/personal-center?sslMode=REQUIRED&characterEncoding=UTF-8&connectionTimeZone=GMT%2B8&forceConnectionTimeZoneToSession=true
    username: root
    password: root
  application:
    name: user-center
  #session 失效时间（分）
  session:
    timeout: 86400
    store-type: redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

